### ISSUE TITLE
Mod does not appear in admin?

### ISSUE THREAD

**Issue by djixas** [progammer-rkt/Rkt_SbCache#1]
Hi,

Should this mod appear anywhere in the magento settings? I have installed it but can't wait any settings or anything other than in "Disable Modules Output".

So not sure if it works or not as Google Page Speed test results in same score, server response time, etc

**Comment by rajeev-k-tomy** [comment]
@djixas I am sorry, I really don't get your question. This module is used to cache Magento static blocks. There are no settings needed for this extension. Once you installed this extension, you need to flush the cache and then you are good to go.
