### ISSUE TITLE
v1.9.3.7 not working

### ISSUE THREAD

**Issue by jgilbert99** [progammer-rkt/Rkt_SbCache#10]
If I navigate to two different categories, the subcategories displayed do not change. I only see the subcategories from the first category. As a temporary fix I have disabled Blocks HTML output on the cache management page.

Does anyone know why this doesn't work on 1.9.3.7?

**Comment by beenfishinglately** [comment]
I am having the same problem with 1.9.3.6 with no luck using this plugin.

**Comment by rajeev-k-tomy** [comment]
I am closing this issue since there exists the same issue report. Please follow up the **[old issue thread](https://github.com/progammer-rkt/Rkt_SbCache/issues/9)** for more details
