### ISSUE TITLE
Some own blocks were still not caching. 

### ISSUE THREAD

**Issue by Webmasterei** [progammer-rkt/Rkt_SbCache#2]
Please add 
rand(0,9999999) or something similarly random on line 57 in Oberver.php. 

For some self-written content block it didn't work otherwise since the key wasn't unique.

**Comment by rajeev-k-tomy** [comment]
Thanks for notifying this. I have added a random string of length 5 with the cache key, so that the key become more unique. Hopes that will generate a unique cache key for every static block even if they are using same identifier.
